<?php
require_once __DIR__.'/../config/auth.php';
if(customer() && subscription_active(customer())){header('Location: /generator.php');exit;}
$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$u=trim($_POST['username']??'');$p=$_POST['password']??'';$s=$pdo->prepare('SELECT * FROM customers WHERE username=?');$s->execute([$u]);$c=$s->fetch();if($c&&password_verify($p,$c['password_hash'])&&subscription_active($c)){session_regenerate_id(true);$_SESSION['customer_id']=(int)$c['id'];header('Location: /generator.php');exit;}$error='Login gagal atau masa langganan sudah berakhir.';}
$wa='6282396875282';$msg=rawurlencode('Halo, saya ingin berlangganan QRIS Generator Rp700.000/bulan. Mohon informasi pembayaran dan aktivasi.');
?><!doctype html><html lang="id"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>QRIS Generator</title>
<style>body{font-family:Arial;background:#f2f3f5;display:grid;place-items:center;min-height:100vh}.c{width:min(420px,92vw);background:#fff;padding:28px;border-radius:16px;box-shadow:0 12px 40px #0002}.price{font-size:28px;font-weight:800}input,button,a{width:100%;padding:13px;margin:6px 0;box-sizing:border-box;border-radius:8px}input{border:1px solid #ccc}button{background:#111;color:#fff;border:0;font-weight:bold}.wa{display:block;text-align:center;text-decoration:none;background:#16a34a;color:#fff;font-weight:bold}.err{background:#fee2e2;color:#991b1b;padding:10px;border-radius:8px}</style>
<div class="c"><h1>QRIS Generator</h1><div class="price">Rp700.000 / bulan</div><p>Akses hanya untuk pelanggan aktif.</p><?php if($error):?><div class="err"><?=e($error)?></div><?php endif;?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input name="username" placeholder="Username" required><input name="password" type="password" placeholder="Password" required><button>Masuk</button></form><a class="wa" href="https://wa.me/<?=$wa?>?text=<?=$msg?>" target="_blank">Berlangganan via WhatsApp</a></div>
