<?php
require_once __DIR__.'/../config/auth.php';require_admin();$msg='';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'';$id=(int)($_POST['customer_id']??0);
if($action==='create'){ $name=trim($_POST['name']??'');$wa=trim($_POST['whatsapp']??'');$u=trim($_POST['username']??'');$p=$_POST['password']??'';if($name&&$wa&&$u&&strlen($p)>=8){try{$s=$pdo->prepare('INSERT INTO customers(name,whatsapp,username,password_hash) VALUES(?,?,?,?)');$s->execute([$name,$wa,$u,password_hash($p,PASSWORD_DEFAULT)]);$msg='Pelanggan dibuat.';}catch(Throwable $e){$msg='Gagal membuat pelanggan.';}}else{$msg='Lengkapi data; password minimal 8 karakter.';}}
if($action==='extend'){ $days=(int)($_POST['days']??30);if(!in_array($days,[30,60,90,365],true))$days=30;$s=$pdo->prepare('SELECT * FROM customers WHERE id=?');$s->execute([$id]);$c=$s->fetch();if($c){$old=$c['subscription_expiry'];$base=($old&&strtotime($old)>time())?strtotime($old):time();$new=date('Y-m-d H:i:s',$base+$days*86400);$start=$c['subscription_start']?:date('Y-m-d H:i:s');$pdo->prepare("UPDATE customers SET status='active',subscription_start=?,subscription_expiry=? WHERE id=?")->execute([$start,$new,$id]);$pdo->prepare('INSERT INTO subscription_logs(customer_id,action,days,old_expiry,new_expiry) VALUES(?,?,?,?,?)')->execute([$id,$old?'extend':'activate',$days,$old,$new]);$msg='Langganan diperpanjang.';}}
if($action==='suspend'){$pdo->prepare("UPDATE customers SET status='suspended' WHERE id=?")->execute([$id]);$msg='Akun disuspend.';}
if($action==='unsuspend'){$pdo->prepare("UPDATE customers SET status='active' WHERE id=?")->execute([$id]);$msg='Akun diaktifkan kembali.';}}
$customers=$pdo->query('SELECT * FROM customers ORDER BY id DESC')->fetchAll();
?><!doctype html><html lang="id"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:Arial;background:#f3f4f6}.wrap{max-width:1100px;margin:25px auto;padding:0 15px}.card{background:#fff;padding:18px;border-radius:12px;margin-bottom:15px;overflow:auto}input,select,button{padding:9px;margin:3px;border-radius:7px;border:1px solid #ccc}button{background:#111;color:#fff;border:0}.green{background:#008f45}.red{background:#d71920}table{border-collapse:collapse;width:100%;min-width:800px}th,td{padding:9px;border-bottom:1px solid #ddd;text-align:left;font-size:13px}</style><div class="wrap"><h1>Dashboard Admin</h1><div class="card"><h2>Tambah Pelanggan</h2><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="create"><input name="name" placeholder="Nama" required><input name="whatsapp" placeholder="WhatsApp" required><input name="username" placeholder="Username" required><input name="password" type="password" placeholder="Password min 8" required><button class="green">Buat Akun</button></form></div><div class="card"><h2>Pelanggan</h2><table><tr><th>Nama</th><th>Username</th><th>WA</th><th>Status</th><th>Berakhir</th><th>Aksi</th></tr><?php foreach($customers as $c):$active=subscription_active($c);?><tr><td><?=e($c['name'])?></td><td><?=e($c['username'])?></td><td><?=e($c['whatsapp'])?></td><td><?=e($c['status'])?> / <?=$active?'AKTIF':'EXPIRED'?></td><td><?=e($c['subscription_expiry']??'-')?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="customer_id" value="<?=$c['id']?>"><input type="hidden" name="action" value="extend"><select name="days"><option value="30">30 hari</option><option value="60">60 hari</option><option value="90">90 hari</option><option value="365">365 hari</option></select><button class="green">Aktif/Perpanjang</button></form><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="customer_id" value="<?=$c['id']?>"><input type="hidden" name="action" value="<?=$c['status']==='suspended'?'unsuspend':'suspend'?>"><button class="<?=$c['status']==='suspended'?'green':'red'?>"><?=$c['status']==='suspended'?'Unsuspend':'Suspend'?></button></form></td></tr><?php endforeach;?></table></div></div>
